[package]
name = "scrfd"
version = "0.1.0"
edition = "2021"

[features]
default = ["image/default"]

[dependencies]
anyhow = "1.0.98"
image = { version = "0.25.0", default-features = false }
tract-onnx = "0.20.0"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
codegen-units = 1
